### ISSUE TITLE
Update a task

### ISSUE THREAD

**Issue by AlbaPi** [TheRosettaFoundation/SOLAS-Match#1180]
Everytime I update a task it appears: Oops! there has been a technical problem.

Slim Application Error
Message:Undefined index: alsoViewedTasksCount
Loc: /repo/solas-match/ui/templating/templates_compiled/fe9acd1bda33bd551da7693022e076cc3075e6bb.file.task.view.tpl.php
Line: 153
Code: 8

Trace: 

0 /repo/solas-match/ui/templating/templates_compiled/fe9acd1bda33bd551da7693022e076cc3075e6bb.file.task.view.tpl.php(153): Slim\Slim::handleErrors(8, 'Undefined index...', '/repo/solas-mat...', 153, Array) 
1 /repo/solas-match/ui/vendor/smarty/smarty/distribution/libs/sysplugins/smarty_internal_templatebase.php(182): content_5562c60dd21db2_60914750(Object(Smarty_Internal_Template)) 
2 /repo/solas-match/ui/vendor/slim/views/Slim/Views/Smarty.php(90): Smarty_Internal_TemplateBase->fetch('task/task.view....', NULL) 
3 /repo/solas-match/ui/vendor/slim/slim/Slim/View.php(255): Slim\Views\Smarty->render('task/task.view....', NULL) 
4 /repo/solas-match/ui/vendor/slim/slim/Slim/View.php(243): Slim\View->fetch('task/task.view....', NULL) 
5 /repo/solas-match/ui/vendor/slim/slim/Slim/Slim.php(751): Slim\View->display('task/task.view....') 
6 /repo/solas-match/ui/RouteHandlers/TaskRouteHandler.class.php(1429): Slim\Slim->render('task/task.view....') 
7 [internal function]: SolasMatch\UI\RouteHandlers\TaskRouteHandler->taskView('7081') 
8 /repo/solas-match/ui/vendor/slim/slim/Slim/Route.php(441): call_user_func_array(Array, Array) 
9 /repo/solas-match/ui/vendor/slim/slim/Slim/Slim.php(1314): Slim\Route->dispatch() 
10 /repo/solas-match/ui/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() 
11 /repo/solas-match/ui/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() 
12 /repo/solas-match/ui/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call() 
13 /repo/solas-match/ui/vendor/slim/slim/Slim/Slim.php(1261): Slim\Middleware\SessionCookie->call() 
14 /repo/solas-match/index.php(191): Slim\Slim->run() 
15 {main}

Even though, it seems that the changes are done.

**Comment by Wasala** [comment]
Fixed in the develop branch.

**Comment by AlbaPi** [comment]
It is still showing the same message. I've already log out and log in again.

**Comment by Wasala** [comment]
@AlbaPi It is not merged to the master branch yet and live site has not yet been updated too. I will let you know once I deploy this to the live site.

**Comment by AlbaPi** [comment]
Ok! Sorry, I didn't know that I had to wait until the update! Thank you so much! :)
